# Generated by Django 5.2.4 on 2025-07-16 20:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DynamicForm',
            new_name='Form',
        ),
        migrations.RenameModel(
            old_name='DynamicField',
            new_name='FormField',
        ),
    ]
